### ISSUE TITLE
Create custom aliases?

### ISSUE THREAD

**Issue by nickyhajal** [bitkompagniet/vscode_extension_quick_require#5]
Is there anyway to add a custom module alias (like in Node Requirer for Sublime)?

Thanks!

**Comment by kparkov** [comment]
No. But we are open to suggestions. Could you specify it in a bit more details? Is this like `'lodash'` being imported as `_`, but just customizable?

**Comment by nickyhajal** [comment]
Yep - exactly. Similar to the "aliases" section of the options here: https://github.com/ganemone/NodeRequirer/

For example, I have some additions like: 

```
"react-css-modules": "CSSModules",
"react-fa": "{ Icon }",
```

Thanks for your response and help!

**Comment by kparkov** [comment]
I've accepted it. It's going into the next version. 👍  And you're welcome. Keep creating issues. It helps me figuring out what works and what doesn't.
